export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <>
    <h1>projectffsf</h1>
    <p>
      this | that | the other thing
    </p>
    {children}
    </>
  )
}
